lang: ruby
before_script:
  # workaround to fix rake not found
  - gem install rake
deploy:
  provider: s3
  access-key-id: $AWS_ACCESS_KEY_ID
  secret-access-key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET_NAME
  skip-cleanup: true
  region: $AWS_REGION
  acl: public_read